"""
    Pinterest Board Metric Scraper
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Get metrics for a list of Pinterest boards provided as a text file with
    one board url per line (as generated by pinterest_get_links.py)
    Usage::
        python pinterest_get_metrics.py input_file.txt results.csv
"""

from bs4 import BeautifulSoup
import requests
from selenium import webdriver
import time
import csv
import click

@click.command()
@click.argument('source_file')
@click.argument('results_csv')
def get_pinterest_metrics(source_file, results_csv):
    url_base = 'http://www.pinterest.com'

    with open(source_file) as f:
        links = [url_base + item.strip() for item in f]

    with open(results_csv, 'wb') as f:
        fieldnames = ['url', 'pins','followers']
        writer = csv.DictWriter(f,fieldnames=fieldnames)
        writer.writeheader()
        for i, link in enumerate(links):
            print i, link
            row = {}
            r  = requests.get(link)
            data = r.content
            soup = BeautifulSoup(data, "lxml")
            row['url'] = link
            row['pins'] = soup.find("div", class_="pinCount").find('span').string
            row['followers'] = soup.find("div", class_="followerCount").find('span').string
            writer.writerow(row)

if __name__ == '__main__':
    get_pinterest_metrics()

